Changes made to the Homepage
shivshankar9/Student-portal pull request #68
Opened 2021-12-15 06:47 UTC by smridhiwho

I made the following changes:

-  changed the background, and the navigation bar  
- added some text & animation to the landing page. 
- added an about section at the ended of the homepage 
- copied the nav-bar changes to the "Image to pdf" page as well

2021-12-15 14:27 UTC, thepranaygupta requested changes

2021-12-15 14:27 UTC, thepranaygupta commented on home.css
>    margin: 20px 0;
change the values in px to rem

2021-12-16 09:24 UTC, aakankshabhende commented
@smridhiwho can you please put the git page link here

2021-12-16 11:11 UTC, smridhiwho commented on home.css
>    margin: 20px 0;
Sure

2021-12-16 11:11 UTC, smridhiwho commented on home.css
>    margin: 20px 0;
Okay

2021-12-16 15:22 UTC, smridhiwho commented
> @smridhiwho can you please put the git page link here

Done.

2021-12-17 04:12 UTC, aakankshabhende commented
Great work :) @smridhiwho , just resolve the branch conflicts

2021-12-22 17:36 UTC, thepranaygupta approved these changes
LGTM 👍

2021-12-26 06:18 UTC, Abirpal202049 approved these changes

2021-12-29 06:14 UTC, saikatmu31 approved these changes

2021-12-31 04:20 UTC, aakankshabhende commented
Please resolve the conflicts of this branch to get it merged in the main @smridhiwho

2021-12-31 10:44 UTC, Abirpal202049 commented
Make the changes after pulling the latest changes

2022-01-03 12:19 UTC, closed without merging