User can now navigate back to home page
shivshankar9/Student-portal pull request #70
Opened 2021-12-15 11:19 UTC by satyamgupta1495

Users can now navigate back to the home page and also fixed some minor alignment issues.

2021-12-15 13:56 UTC, Abirpal202049 requested changes

2021-12-15 13:56 UTC, Abirpal202049 commented on contact.html
>      <title>Document</title>
Change the title of the page

2021-12-15 13:56 UTC, Abirpal202049 commented on open.css
> +  background-size: cover;
Targed the body by class or id

2021-12-15 14:23 UTC, thepranaygupta approved these changes
just update the page title

2021-12-16 15:47 UTC, satyamgupta1495 commented
is there any more changes required?

2021-12-25 08:29 UTC, shivshankar9 commented
Resolve conflicts @satyamgupta1495

2021-12-26 05:03 UTC, satyamgupta1495 commented
> Resolve conflicts @satyamgupta1495

Don't have the write access. Can you tell me how can I resolve it?

2021-12-26 10:45 UTC, Abirpal202049 approved these changes

2021-12-26 10:48 UTC, merged