logo changed
shivshankar9/Student-portal pull request #75
Opened 2021-12-17 11:47 UTC by 9Shalini

fixes #23
![Screenshot (54)](https://user-images.githubusercontent.com/87543203/146540185-c1ac1b39-cb17-4ed6-a5ef-4a71f8affab9.png)
@shivshankar9

2021-12-18 04:56 UTC, aakankshabhende requested changes

2021-12-18 04:56 UTC, aakankshabhende commented on index.html
> +        <img class="logo" src="slogo.png" alt="">
Can you please keep the logo with the white background? Keep it as it is, that is, logo.png @9Shalini

2021-12-19 07:37 UTC, 9Shalini commented
![Screenshot (68)](https://user-images.githubusercontent.com/87543203/146667440-3381910f-8dc1-4726-82f7-9d372928532f.png)
have made changes accordingly, please check @aakankshabhende

2021-12-19 07:39 UTC, aakankshabhende approved these changes

2021-12-19 11:39 UTC, shivshankar9 approved these changes

2021-12-19 11:40 UTC, merged